### ISSUE TITLE
User can easily navigate to other pages in the app

### ISSUE THREAD

**Issue by i2xzy** [fac-13/Well-Bean#20]
User Stories:
* [x] User can get to Inspire page from all other pages #21
* [x] User can get to Challenges page from all other pages #22
* [x] User can get to Home page from all other pages  #23
* [x] User can get to Stats page from all other pages #24
