### ISSUE TITLE
User can see latest message, 10 latest challenges or current challenge all in one home page

### ISSUE THREAD

**Issue by i2xzy** [fac-13/Well-Bean#29]
User stories:
* [ ] User can see latest inspirational message on home page #30
* [ ] User can see 10 latest challenges in a carousel on home page #31
* [x] User can see their current challenge on the home page #32
* [ ] User will be prompted if they are sure they wish to abandon their current challenge
* [ ] User will receive confirmation that they have completed or abandoned a challenge
