### ISSUE TITLE
The user can view a list of challenges, see more details, opt-in then complete or opt-out a challenge

### ISSUE THREAD

**Issue by n1c0z** [fac-13/Well-Bean#4]
User Stories:

* [x] User can view challenges #13 
* [x] User can select a challenge and see more details #14
* [x] User can opt-in to a challenge #15
* [x] User can mark a challenge as complete #16
* [x] User can opt-out of a challenge if they want #17
